## Justfile - for build orchestration
##     Copyright (C) 2024 - 2026  Kıvılcım İpek Afet Öztürk
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.

set unstable := true

# for compiling Lua

lua := require("luajit") || require("./lua")
luac := require("luac")
luarocks := require("luarocks")
luacheck := require("luacheck")

# for testing environment

podman := require("podman")
busted := require("busted")
cargo := require("cargo")

# for documentation

lualatex := which("lualatex")

# to hook up lament itself

lament := "src/cli/lament"

default:
    just -l

[doc('Sets up required programs for the environment')]
[group("util")]
setup-env:
    true

[doc("Lints the rockspec.")]
[group("lint")]
[group("test")]
lint-rockspec:
    {{ luarocks }} lint lament-*.rockspec
    @echo "{{ UNDERLINE + GREEN + BOLD }}Successfully linted rockspec.{{ NORMAL }}"

[doc("Lints the source code for the project.")]
[group("lint")]
[group("test")]
lint-source:
    {{ luacheck }} src/*
    @echo "{{ UNDERLINE + GREEN + BOLD }}Successfully linted source code.{{ NORMAL }}"

[doc("Lints tests under spec/")]
[group("lint")]
[group("test")]
lint-tests:
    {{ luacheck }} spec/*
    @echo "{{ UNDERLINE + GREEN + BOLD }}Successfully linted tests.{{ NORMAL }}"

[doc("Lints the project.")]
[group("lint")]
[group("test")]
lint: lint-rockspec lint-source lint-tests
    @echo "{{ UNDERLINE + GREEN + BOLD }}Linting done.{{ NORMAL }}"

[doc("Checks the testing framework for bugs.")]
[group("test")]
check-busted FORMAT="utfTerminal":
    {{ busted }} -v -o {{ FORMAT }} spec/check_busted_spec.lua
    @echo "{{ UNDERLINE + GREEN + BOLD }}busted passed the bug check test.{{ NORMAL }}"

[doc("Runs tests")]
[group("test")]
test FORMAT="utfTerminal": check-busted
    {{ busted }} -v -o {{ FORMAT }}
    @echo "{{ UNDERLINE + GREEN + BOLD }}Tests passed.{{ NORMAL }}"

[doc("Compiles the project documentation.")]
[group("build")]
doc-build:
    mkdir -p docs/out
    {{ lualatex }} --halt-on-error --interaction=nonstopmode --output-directory=docs/out docs/README.tex

build-sandbox:
    {{ cargo }} build --manifest-path src/crates/lament_sandbox/Cargo.toml

[doc("Builds the project.")]
[group("build")]
build: setup-env test build-sandbox
    {{ luarocks }} build

[doc("Cleans the artifacts generated by build tasks.")]
[group("build")]
clean:
    {{ luarocks }} remove --force lament || true
    rm -f *.rock *.rockspec~
    rm -f docs/out/* docs/chapters/*.aux docs/chapters/*.log docs/chapters/*.toc docs/chapters/*.dvi
    rm -f docs/*.aux docs/*.log docs/*.toc docs/*.dvi docs/*.fdb_latexmk docs/*.fls

[doc("Executes the project")]
[group("exec")]
run *args:
    LUA_PATH="./src/?.lua;./src/?/init.lua;;" \
    LUA_CPATH="./src/crates/lament_sandbox/target/debug/lib?.so;;" \
    {{ lament }} {{ args }}
