## test/env/Containerfile - hosts a testing environment for tests that will run in the containerized environment
##     Copyright (C) 2024-2025  Kıvılcım İpek Defne Öztürk
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM docker.io/library/alpine:3.23 as stage1
COPY ../.. /usr/share/lament

FROM docker.io/library/alpine:3.23 as stage2


RUN apk add lua grub rustup && sh /usr/share/lament/install-lexpect.sh

WORKDIR /usr/share/lament
ENTRYPOINT [ "/bin/sh" ]
